### ISSUE TITLE
 How can I register this plugin in my program?

### ISSUE THREAD

**Issue by wyl221** [YtFlow/YtFlowTunnel#1]
Can this component run? Or not finished? 
Can you give a test program?

**Comment by bdbai** [comment]
This component is only a prove of concept that UWP VPN API can be used to handle Shadowsocks and demonstrates the basic idea. Some implementation detail like cryptography or AEAD is not covered yet.

To make use of this component, you may need to create a UWP app to register the background task and change server address/port in the code. The only supported server mode is ShadowsocksR with protocol=origin, method=none and obfs=plain. 

Should you have any problem regarding the app, please refer to the following repo which successfully registers a VpnClient on Windows 10 platform.
https://github.com/Noisyfox/ShadowsocksUWP

Alternatively you can join [@YtFlow on Telegram](https://telegram.me/ytflow) to get support.

**Comment by wyl221** [comment]
hi,bdbai 
I created a Test based on the ShadowsocksUWP program,it can be run,but plugins cannot connect, code in Connect is not run.
the code in button_Click:
`var _BKAppTrigger = new ApplicationTrigger();`
`string entryPoint = "YtFlowTunnel.VpnTask";`
`string taskName = "VpnTask";`
`BackgroundTaskRegistration task = await RegisterBackgroundTask(entryPoint, taskName, _BKAppTrigger, null);`
`ApplicationTriggerResult apptr = await _BKAppTrigger.RequestAsync();`
`VpnManagementAgent mgragent = new VpnManagementAgent();`
`VpnPlugInProfile profile = new VpnPlugInProfile() {`
`AlwaysOn = true,`
`ProfileName = "YtFlowTunnel",`
`VpnPluginPackageFamilyName = "YtFlowTunnel",`
`RememberCredentials = true,`
`RequireVpnClientAppUI = true,`
` };`
`VpnManagementErrorStatus profileErrStatus = await mgragent.AddProfileFromObjectAsync(profile);`
`VpnManagementErrorStatus connectErrStatus =  await mgragent.ConnectProfileAsync(profile);`

Is there any error in the code? I think I have the same questions that you asked at MSDN.
[https://social.msdn.microsoft.com/Forums/en-US/26b089e4-2448-42d7-a4fd-0fe65629b352/uwp-questions-about-vpn-plugin?forum=wpdevelop](https://social.msdn.microsoft.com/Forums/en-US/26b089e4-2448-42d7-a4fd-0fe65629b352/uwp-questions-about-vpn-plugin?forum=wpdevelop)
Did you find the answer？please help

**Comment by bdbai** [comment]
Hi wyl221,

Have you tried registering the background task in `Package.appxmanifest` ? `vpnClient` tasks can only [be declared in the manifest](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/declare-background-tasks-in-the-application-manifest) instead of by programming because there is no corresponding trigger provided. [This example](https://github.com/Noisyfox/ShadowsocksUWP/blob/23a6563377e9017908a41b1fdf579a6a2b039382/shadowsocks-uwp/Package.appxmanifest#L24) might help.

After successfully registering a `vpnClient` background task, it is possible to create a new profile via System Settings that will trigger the task. Besides, creating a new profile by programming also works. IMHO `VpnPluginPackageFamilyName` field in your code does not reflect your app's package family name.

For the questions I asked in Microsoft Community:

1. Register a background task first whose entrypoint is set correctly, then call `Windows.Networking.Vpn.ProcessEventAsync` in your background task with parameters to be your IVpnPlugin instance and a `Windows.ApplicationModel.Background.IBackgroundTaskInstance.TriggerDetails` object which is obtained from `Windows.ApplicationModel.Background.IBackgroundTask.Run` argument;
2. Connections from client to Shadowsocks server do not utilize the built-in 2 connection channels;

Regards,
bdbai
